baseURL = "/"
languageCode = "id"
title = "Cora & Edoardo"
theme = "seminyak"

[params]
  theme_color = "#fcfbeb"
  color_palette = "yellow"
  background_image_url = "images/cp2019_c.png"
  referrer_policy = "same-origin"
  google_fonts = "Oswald|Raleway"
